=== Jeroo/TrabajoIntermedioXML/web/1.2_TiendasLavadoras/DTD_ListaTiendasLavadoras.dtd
<?xml version='1.0' encoding='UTF-8' ?> 
<!-- was: <?xml version='1.0' encoding="windows-1252" ?> --> 
<!--DTD externo para el ejercicio: 1.2  tiendas-->
<!--- Entidad para el tipo PCDATA -->
<!ENTITY  % pcd "(#PCDATA)">
<!--- Entidad para el tipo CDATA -->
<!ENTITY  % cd "CDATA">
<!--- elemento principal -->
<!ELEMENT listaTiendasLavadoras (tiendaLavadoras*)>
<!--- elementos de la rama tienda -->
<!ELEMENT  tiendaLavadoras (nombreTienda,direcciónTiendaLavadoras,teléfono+,fax*,distribuidor*,lavadora+)>
<!ELEMENT  nombreTienda %pcd;>
<!--- elementos de la rama direcci�n -->
<!ELEMENT  direcciónTiendaLavadoras ((calle|avenida),localidad,códigoPostal,país)>
<!ELEMENT  calle (nombreCalle,númeroCalle)>
<!ELEMENT  númeroCalle %pcd;>
<!ELEMENT  nombreCalle %pcd;>
<!ELEMENT  avenida (nombreAvenida,númeroAvenida)>
<!ELEMENT  nombreAvenida %pcd;>
<!ELEMENT  númeroAvenida %pcd;>
<!ELEMENT  localidad %pcd;>
<!ELEMENT  códigoPostal %pcd;>
<!ELEMENT  país %pcd;>
<!ELEMENT  teléfono %pcd;>
<!ELEMENT  fax %pcd;>


<!--- elementos de la rama Distribuidor -->
<!ELEMENT  distribuidor (direcciónDistribuidor,marcasOficiales)>
<!ELEMENT  direcciónDistribuidor ((calleDistribuidor|avenidaDistribuidor),localidadDistribuidor,códigoPostalDistribuidor,paísDistribuidor)>
<!ELEMENT  calleDistribuidor (nombreCalleDistribuidor,númeroCalleDistribuidor)>
<!ELEMENT  númeroCalleDistribuidor %pcd;>
<!ELEMENT  nombreCalleDistribuidor %pcd;>
<!ELEMENT  avenidaDistribuidor (nombreAvenidaDistribuidor,númeroAvenidaDistribuidor)>
<!ELEMENT  nombreAvenidaDistribuidor %pcd;>
<!ELEMENT  númeroAvenidaDistribuidor %pcd;>
<!ELEMENT  localidadDistribuidor %pcd;>
<!ELEMENT  códigoPostalDistribuidor %pcd;>
<!ELEMENT  paísDistribuidor %pcd;>
<!ELEMENT  marcasOficiales (NombreMarca*)>
<!ELEMENT  NombreMarca %pcd;>
<!ATTLIST distribuidor
    nombre %cd; #REQUIRED   
  >

<!--- elementos de la rama Lavadora -->
<!ELEMENT  lavadora %pcd;>
<!ATTLIST lavadora
     códigoMmodelo %cd; #REQUIRED
     cargaMáxima %cd; #REQUIRED
     marca %cd; #REQUIRED
  >

=== Jeroo/TrabajoIntermedioXML/web/1.2_TiendasLavadoras/1.2_TiendasLavadoras_correcto.xml
<?xml version="1.0" encoding="windows-1252" ?>
<!DOCTYPE listaTiendasLavadoras SYSTEM "DTD_ListaTiendasLavadoras.dtd">
<listaTiendasLavadoras>
    <tiendaLavadoras>
        <nombreTienda>Tienda de lavadoras la mejor opción del lavado</nombreTienda>
        <direcciónTiendaLavadoras>
            <calle>
                <nombreCalle>Primera</nombreCalle>
                <númeroCalle>58</númeroCalle>
            </calle>
            <localidad>
                Santo Domingo
            </localidad>
            <códigoPostal>
                50002
            </códigoPostal>
            <país>
                Rep. Dom.
            </país>
        </direcciónTiendaLavadoras>        
        <teléfono>829-654-7854</teléfono>
        <fax>809-654-7896</fax>
        <distribuidor nombre="distribuidor1">
            <direcciónDistribuidor>
                <calleDistribuidor>
                    <nombreCalleDistribuidor>La inocencia</nombreCalleDistribuidor>
                    <númeroCalleDistribuidor>36</númeroCalleDistribuidor>
                </calleDistribuidor>
                <localidadDistribuidor>
                    Santo Domingo
                </localidadDistribuidor>
                <códigoPostalDistribuidor>
                    60054
                </códigoPostalDistribuidor>
                <paísDistribuidor>
                    Rep. Dom.
                </paísDistribuidor>
            </direcciónDistribuidor>
            <marcasOficiales>
                 <NombreMarca>Marca 1</NombreMarca>  
                 <NombreMarca>Marca 2</NombreMarca>   
                 <NombreMarca>Marca 3</NombreMarca>
            </marcasOficiales>
        </distribuidor>
         <distribuidor nombre="distribuidor2"> 
                   <direcciónDistribuidor>
                <calleDistribuidor>
                    <nombreCalleDistribuidor>La piedad</nombreCalleDistribuidor>
                    <númeroCalleDistribuidor>562</númeroCalleDistribuidor>
                </calleDistribuidor>
                <localidadDistribuidor>
                    Barahona
                </localidadDistribuidor>
                <códigoPostalDistribuidor>
                    84500
                </códigoPostalDistribuidor>
                <paísDistribuidor>
                    Rep. Dom.
                </paísDistribuidor>
            </direcciónDistribuidor>          
            <marcasOficiales>
                 <NombreMarca>Marca 4</NombreMarca>  
                 <NombreMarca>Marca 5</NombreMarca>   
                 <NombreMarca>Marca 6</NombreMarca>
            </marcasOficiales>
        </distribuidor>
        <lavadora códigoMmodelo="cod-modelo-1" cargaMáxima="15kg" marca="Samsung"/>  
        <lavadora códigoMmodelo="cod-modelo-2" cargaMáxima="10kg" marca="Bosch"/>  
        <lavadora códigoMmodelo="cod-modelo-3" cargaMáxima="25kg" marca="Electrolux"/>     
    </tiendaLavadoras>
     <tiendaLavadoras>
        <nombreTienda>Tienda de lavadoras la excelente</nombreTienda>
        <direcciónTiendaLavadoras>
            <avenida>
                <nombreAvenida>27 de Febrero</nombreAvenida>
                <númeroAvenida>46</númeroAvenida>
            </avenida>
            <localidad>
                Santo Domingo
            </localidad>
            <códigoPostal>
                90002
            </códigoPostal>
            <país>
                Rep. Dom.
            </país>
        </direcciónTiendaLavadoras>        
        <teléfono>809-554-8456</teléfono>
        <fax>809-554-8457</fax>
        <distribuidor nombre="distribuidor3">
            <direcciónDistribuidor>
                <calleDistribuidor>
                    <nombreCalleDistribuidor>La ignorancia</nombreCalleDistribuidor>
                    <númeroCalleDistribuidor>14</númeroCalleDistribuidor>
                </calleDistribuidor>
                <localidadDistribuidor>
                    San Pedro de Macoris
                </localidadDistribuidor>
                <códigoPostalDistribuidor>
                    40054
                </códigoPostalDistribuidor>
                <paísDistribuidor>
                    Rep. Dom.
                </paísDistribuidor>
            </direcciónDistribuidor>
            <marcasOficiales>
                 <NombreMarca>Marca 4</NombreMarca>  
                 <NombreMarca>Marca 5</NombreMarca>   
                 <NombreMarca>Marca 6</NombreMarca>
            </marcasOficiales>
        </distribuidor>
         <distribuidor nombre="distribuidor4"> 
                   <direcciónDistribuidor>
                <calleDistribuidor>
                    <nombreCalleDistribuidor>La Luz</nombreCalleDistribuidor>
                    <númeroCalleDistribuidor>88</númeroCalleDistribuidor>
                </calleDistribuidor>
                <localidadDistribuidor>
                    Santiago de los Caballeros
                </localidadDistribuidor>
                <códigoPostalDistribuidor>
                    63500
                </códigoPostalDistribuidor>
                <paísDistribuidor>
                    Rep. Dom.
                </paísDistribuidor>
            </direcciónDistribuidor>          
            <marcasOficiales>
                 <NombreMarca>Marca 7</NombreMarca>  
                 <NombreMarca>Marca 8</NombreMarca>   
                 <NombreMarca>Marca 9</NombreMarca>
            </marcasOficiales>
        </distribuidor>
        <lavadora códigoMmodelo="cod-modelo-4" cargaMáxima="8kg" marca="Fagor"/>  
        <lavadora códigoMmodelo="cod-modelo-5" cargaMáxima="23kg" marca="Aeg"/>  
        <lavadora códigoMmodelo="cod-modelo-6" cargaMáxima="36kg" marca="Beko"/>     
    </tiendaLavadoras>
</listaTiendasLavadoras>
