=== Jeroo/TrabajoIntermedioXML/web/1.3_DTD_y_Schema/1.3_lista_asignatura.dtd
<?xml version="1.0"  encoding="windows-1252"?>

<!ELEMENT Lista (Asignatura|Alumno)*>
<!ELEMENT Alumno (Apellidos|Nombre)*>
<!ATTLIST Alumno id CDATA #IMPLIED >
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Apellidos (#PCDATA)>
<!ELEMENT Asignatura (#PCDATA|Hora|Día)*>
<!ATTLIST Asignatura codigo CDATA #IMPLIED >
<!ELEMENT Día (#PCDATA)>
<!ELEMENT Hora (#PCDATA)>

=== Jeroo/TrabajoIntermedioXML/web/1.3_DTD_y_Schema/1.3_DTD_Schema_Incorrecto.xml
<?xml version="1.0" encoding="windows-1252" ?>
<!DOCTYPE Lista SYSTEM "1.3_lista_asignatura.dtd">

<!--Lista xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="1.3_lista_asignaturas_schema.xsd"-->
<Lista>
    <Alumno id="1">
        <Nombre>Arturo</Nombre> 
        <Apellidos>Pérez Rubio</Apellidos>
    </Alumno>
     <Alumno id="3">
        <Nombre>Salvador</Nombre> 
    </Alumno>
    <Alumno id="2">
        <Apellidos>Rodríguez García</Apellidos> 
        <Nombre>Manuel</Nombre>
    </Alumno>
    <Alumno id="6">
        <Apellidos>Lozano Gómez</Apellidos> 
        <Nombre>Sara</Nombre>
    </Alumno>
    <Asignatura codigo="059">
        Inglés 
        <Día>Domingo</Día> 
        <Hora>12:00</Hora>
    </Asignatura>
     <Asignatura codigo="059">
        Frances 
        <Día>Domingo</Día> 
    </Asignatura>
</Lista>
